services:
    php:
        image: serversideup/php:8.3-fpm-nginx-alpine
        environment:
            PHP_OPCACHE_ENABLE: "1"
        networks:
            - web-public
        volumes:
            - "storage_private:/var/www/html/storage/app/private/"
            - "storage_public:/var/www/html/storage/app/public/"
            - "storage_sessions:/var/www/html/storage/framework/sessions"
            - "storage_logs:/var/www/html/storage/logs"

volumes:
    storage_private:
    storage_public:
    storage_sessions:
    storage_logs:

networks:
    web-public:
